language: node_js
node_js:
- '0.11'
script: grunt test
deploy:
  provider: npm
  email: mugo@forfuture.co.ke
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: Yep+UnYxHBi6SKAjwEj1hIK1rV/fp8Y5nxi/Y1x+ZxpuyE29qJux1FkJUSAa6uIhIwW+qUWsXnwzsao7HYFlGPg7hV6GCnARpsLv3TbIVbNeJiq4SXfUAQxeUUKlhKaHOWq1emGM18aHFSYTZ9JKZzJ6n1P8lhaqrJy417lF7TQ=
before_deploy:
- cp package.json dist/
- ls | grep -v "dist" | xargs -I{} rm -rf {}
- cp -rf dist/* .
- rm -rf dist/
